# Generated by Django 5.2.8 on 2025-11-24 13:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='is_used',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=users.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='b72e1e6dd9cb4a19af100a608dfb98de', max_length=64, unique=True),
        ),
    ]
