# Generated by Django 5.2.8 on 2025-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='b1d9cb0de69445a3b866058f4749d7f5', max_length=64, unique=True),
        ),
    ]
