# Generated by Django 5.2.8 on 2025-11-26 16:42

from django.db import migrations

def backfill_user_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("users", "Profile")

    for user in User.objects.all():
        # Backfill first/last name if empty
        if not user.first_name:
            user.first_name = "First"
        if not user.last_name:
            user.last_name = "Last"
        user.save()

        # Ensure profile exists
        profile, created = Profile.objects.get_or_create(user=user)
        if not profile.national_id:
            profile.national_id = f"9999{user.id}"  # placeholder ID
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_passwordresettoken_token_profile'),
    ]

    operations = [
        migrations.RunPython(backfill_user_data),
    ]
