# Generated by Django 5.2.8 on 2025-11-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backfill_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='e44a5b0056fe40e989e7a8c635cdd817', max_length=64, unique=True),
        ),
    ]
