# Generated by Django 5.2.8 on 2025-11-22 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
