# Generated by Django 5.2.8 on 2025-11-22 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanrepayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
