# Generated by Django 5.2.8 on 2025-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
