# Generated by Django 5.2.8 on 2025-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_passwordresettoken_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='c097f8ee691f4b7394b8626939698b2f', max_length=64, unique=True),
        ),
    ]
